#!/bin/bash

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0
JS_FILES=$(echo "$FILES" | grep ".js$")
CSS_FILES=$(echo "$FILES" | grep ".scss\|.css")

# Prettify all selected files
if [[ ! -z "$CSS_FILES" ]];
then
  (echo "$CSS_FILES" | xargs node_modules/.bin/prettier --ignore-path .prettierignore --config .prettierrc.json --ignore-unknown --write) || exit 1
fi

if [[ ! -z "$JS_FILES" ]];
then
  (echo "$JS_FILES" | xargs ./node_modules/.bin/prettier --ignore-path .prettierignore --config .prettierrc.json --ignore-unknown --write) || exit 1
  (echo "$JS_FILES" | xargs ./node_modules/.bin/eslint --config .eslintrc.js --fix) || exit 1
fi

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
