name: Build Metronome with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@master
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: Install deps
      run: npm install

    - name: Build
      run: npm run build
